-- Access Codes Table for Super Admin Management
-- Run this in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS access_codes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code TEXT NOT NULL UNIQUE,
    type TEXT NOT NULL CHECK (type IN ('regulator', 'partner', 'demo', 'trial', 'special')),
    recipient_name TEXT NOT NULL,
    recipient_email TEXT NOT NULL,
    recipient_org TEXT DEFAULT '',
    purpose TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL,
    usage_limit TEXT NOT NULL CHECK (usage_limit IN ('single', 'multi', 'unlimited')),
    usage_count INTEGER DEFAULT 0,
    max_usage_count INTEGER,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'expired', 'revoked', 'exhausted')),
    created_by TEXT NOT NULL
);

-- Index for fast lookups
CREATE INDEX IF NOT EXISTS idx_access_codes_code ON access_codes(code);
CREATE INDEX IF NOT EXISTS idx_access_codes_status ON access_codes(status);
CREATE INDEX IF NOT EXISTS idx_access_codes_type ON access_codes(type);
CREATE INDEX IF NOT EXISTS idx_access_codes_expires_at ON access_codes(expires_at);

-- Enable RLS
ALTER TABLE access_codes ENABLE ROW LEVEL SECURITY;

-- Policy for super admin access (service role bypasses RLS)
-- The API uses service role key, so no additional policies needed

-- Grant permissions
GRANT ALL ON access_codes TO service_role;
GRANT SELECT ON access_codes TO authenticated;

-- Comment
COMMENT ON TABLE access_codes IS 'Access codes generated by Super Admin for regulators, partners, demos, and trial users';
